# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788c7d130b6e60d8e9535a67f1047efcb0ba512328a6396bc1c9f6e5bfebb4d4ea17fce91603a5cdcd0fc004ad08655e6958b7d11f8d448786f08e112f766e44

test:
  secret_key_base: bbd5da3da440921851074a45f4a657604308dbc059aac298ceacb851d6d004bd8a54a2b2d1047b552f4524f3ef6eedf0ebbbf18a0a547e1959589034bd9b5417

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
